#!/bin/bash

echo "Setting up splash screen for React Native CLI project..."
echo "======================================================"
echo ""

# Check if splash image exists
if [ ! -f "assets/splash.png" ]; then
    echo "❌ assets/splash.png not found!"
    echo "Please make sure you have your splash screen image in assets/splash.png"
    exit 1
fi

echo "✅ Found splash screen image"
echo ""

echo "📱 Android Splash Screen Setup"
echo "============================="
echo "For Android, you need to:"
echo "1. Create a splash screen drawable"
echo "2. Configure it in android/app/src/main/res/values/styles.xml"
echo ""
echo "Recommended approach: Use react-native-bootsplash"
echo "npm install react-native-bootsplash"
echo "npx react-native-bootsplash init"
echo ""

echo "🍎 iOS Splash Screen Setup"
echo "========================="
echo "For iOS, you can modify:"
echo "  ios/liftbook/LaunchScreen.storyboard"
echo ""
echo "Current setup shows text labels. To add your splash image:"
echo "1. Open LaunchScreen.storyboard in Xcode"
echo "2. Add an ImageView"
echo "3. Set the image to your splash.png"
echo "4. Position it appropriately"
echo ""

echo "🚀 Alternative: Use react-native-bootsplash"
echo "=========================================="
echo "This is the easiest way to set up splash screens:"
echo ""
echo "1. Install the package:"
echo "   npm install react-native-bootsplash"
echo ""
echo "2. Initialize it:"
echo "   npx react-native-bootsplash init"
echo ""
echo "3. This will automatically:"
echo "   - Generate all required splash screen assets"
echo "   - Configure Android and iOS splash screens"
echo "   - Set up the necessary code"
echo ""

echo "💡 Manual Setup Steps"
echo "===================="
echo "If you prefer manual setup:"
echo ""
echo "Android:"
echo "1. Create drawable/splash.xml"
echo "2. Update styles.xml to use splash theme"
echo "3. Add splash image to drawable folder"
echo ""
echo "iOS:"
echo "1. Add splash image to Images.xcassets"
echo "2. Update LaunchScreen.storyboard"
echo "3. Or create a custom splash screen view"
echo ""

echo "🔧 Quick Test"
echo "============="
echo "After setting up splash screen:"
echo "1. Clean build: cd android && ./gradlew clean && cd .."
echo "2. Rebuild: npx react-native run-android"
echo "3. Test on device (splash may not show in simulator)" 